# This is a basic workflow to help you get started with Actions

name: Build Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      VARIAVEL_GLOBAL:
        required: true
        type: string
    outputs:
      VARIAVEL_BUILD:
        value: ${{ jobs.build.outputs.variavel_build_interna }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      variavel_build_interna: ${{ steps.step_outputs.outputs.variavel_build_alterada }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Criando variáveis de ambiente
        run: |
          echo "VARIAVEL_BUILD=${{ inputs.VARIAVEL_GLOBAL }}, valor alterado no build" >> $GITHUB_ENV
          
      # Runs a set of commands using the runners shell
      - name: Criando variáveis Output
        id: step_outputs                
        run: |
          echo "variavel_build_alterada=${{ env.VARIAVEL_BUILD }}" >> $GITHUB_OUTPUT
          echo "Build Finalizado!" >> $GITHUB_STEP_SUMMARY    
          