# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      VARIAVEL_BUILD:
        required: true
        type: string
      VARIAVEL_DEPLOY:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Mostrando variáveis
        run: |
          echo "VARIAVEL_BUILD='${{ inputs.VARIAVEL_BUILD }}'"
          echo "VARIAVEL_DEPLOY='${{ inputs.VARIAVEL_DEPLOY }}'"
          
      # Runs a set of commands using the runners shell
      - name: Finalizando   
        run: |
          echo "Finalizando todo processo!" >> $GITHUB_STEP_SUMMARY
          echo "VARIÁVEL GLOBAL = ${{ inputs }}" >> $GITHUB_STEP_SUMMARY
