# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VARIAVEL_GLOBAL: "iniciada"    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Criando variáveis de ambiente
        run: |
          echo "VARIAVEL_GLOBAL='valor auterado'" >> $GITHUB_ENV
          echo "VARIAVEL_INTERNA='iniciado interna'" >> $GITHUB_ENV
          
      # Runs a set of commands using the runners shell
      - name: Criando variáveis Output
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Mostrando valores das variáveis
        run: |
          echo "env.VARIAVEL_GLOBAL: ${{ env.VARIAVEL_GLOBAL }}"
          echo "VARIAVEL_GLOBAL: $VARIAVEL_GLOBAL"
